Default: &defaults
  user: root
  password: pazyeh
  host: localhost
  port: 3306
  database: latestmy
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: latestmy_test
  <<: *defaults

Staging:
  database: latestmy_staging
  poolsize: 100
  <<: *defaults

Production:
  database: latestmy_production
  poolsize: 100
  <<: *defaults
